"""create models car and service_item

Revision ID: 4c4f17781395
Revises: 
Create Date: 2026-04-14 14:54:38.746512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c4f17781395'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='Date of created'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='Date of last updated'),
    sa.CheckConstraint('length(name) > 0', name='car_name_not_empty'),
    sa.CheckConstraint('mileage >= 0', name='car_mileage_positive'),
    sa.CheckConstraint('year >= 1900', name='car_year_valid'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_item',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('car_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('interval_km', sa.Integer(), nullable=False),
    sa.Column('last_km', sa.Integer(), nullable=False),
    sa.Column('last_date', sa.Date(), nullable=True),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='Date of created'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='Date of last updated'),
    sa.CheckConstraint('(interval_km > 0 OR interval_days > 0)', name='at_least_one_interval'),
    sa.CheckConstraint('interval_days >= 0', name='interval_days_positive'),
    sa.CheckConstraint('interval_km >= 0', name='interval_km_positive'),
    sa.CheckConstraint('last_date IS NULL OR last_date <= CURRENT_DATE', name='last_date_in_past'),
    sa.CheckConstraint('last_km >= 0', name='last_km_positive'),
    sa.CheckConstraint('length(name) > 0', name='service_name_not_empty'),
    sa.ForeignKeyConstraint(['car_id'], ['car.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_item')
    op.drop_table('car')
    # ### end Alembic commands ###
