"""update UniqueCons

Revision ID: 56e067b30efc
Revises: b537bc52c046
Create Date: 2026-05-13 10:41:07.223543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56e067b30efc'
down_revision: Union[str, None] = 'b537bc52c046'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_service_item_car_name'), 'service_item', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_service_item_car_name'), 'service_item', ['car_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
