"""create model car

Revision ID: 77ffbd3edd29
Revises: ce96b039d00a
Create Date: 2026-04-23 19:17:12.367082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '77ffbd3edd29'
down_revision: Union[str, None] = 'ce96b039d00a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('vin', sa.String(length=17), nullable=True),
    sa.Column('license_plate', sa.String(length=20), nullable=True),
    sa.Column('engine_volume', sa.Float(), nullable=True),
    sa.Column('fuel_type', postgresql.ENUM('PETROL', 'DIESEL', 'ELECTRIC', 'GAS', 'HYBRID', name='fueltypeenum'), nullable=True),
    sa.Column('transmission', postgresql.ENUM('MANUAL', 'AUTOMATIC', 'CVT', 'ROBOT', name='transmissionenum'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='Date of created'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='Date of last updated'),
    sa.CheckConstraint('length(name) > 0', name='car_name_not_empty'),
    sa.CheckConstraint('mileage >= 0', name='car_mileage_positive'),
    sa.CheckConstraint('year >= 1900', name='car_year_valid'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vin')
    )
    op.create_index(op.f('ix_car_user_id'), 'car', ['user_id'], unique=False)
    op.create_index('ix_cars_user_archived', 'car', ['user_id', 'is_archived'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cars_user_archived', table_name='car')
    op.drop_index(op.f('ix_car_user_id'), table_name='car')
    op.drop_table('car')
    # ### end Alembic commands ###
