"""create model service_item

Revision ID: 9f4193585610
Revises: 77ffbd3edd29
Create Date: 2026-04-23 19:22:10.961364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f4193585610'
down_revision: Union[str, None] = '77ffbd3edd29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_item',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('car_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=False),
    sa.Column('interval_km', sa.Integer(), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('last_km', sa.Integer(), nullable=False),
    sa.Column('last_date', sa.Date(), nullable=True),
    sa.Column('warn_at', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='Date of created'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='Date of last updated'),
    sa.CheckConstraint('(interval_km > 0 OR interval_days > 0)', name='at_least_one_interval'),
    sa.CheckConstraint('interval_days >= 0', name='interval_days_positive'),
    sa.CheckConstraint('interval_km >= 0', name='interval_km_positive'),
    sa.CheckConstraint('last_date IS NULL OR last_date <= CURRENT_DATE', name='last_date_in_past'),
    sa.CheckConstraint('last_km >= 0', name='last_km_positive'),
    sa.CheckConstraint('length(name) > 0', name='service_name_not_empty'),
    sa.ForeignKeyConstraint(['car_id'], ['car.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('car_id', 'name', name='uq_service_item_car_name')
    )
    op.create_index(op.f('ix_service_item_car_id'), 'service_item', ['car_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_item_car_id'), table_name='service_item')
    op.drop_table('service_item')
    # ### end Alembic commands ###
