"""create model fuel_log

Revision ID: aaedb9475053
Revises: daf16e72481a
Create Date: 2026-04-23 19:25:14.262903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaedb9475053'
down_revision: Union[str, None] = 'daf16e72481a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fuel_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('car_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=False),
    sa.Column('liters', sa.Float(), nullable=False),
    sa.Column('price_per_liter', sa.Float(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('station', sa.String(length=200), nullable=True),
    sa.Column('full_tank', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='Date of created'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='Date of last updated'),
    sa.ForeignKeyConstraint(['car_id'], ['car.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fuel_log_car_id'), 'fuel_log', ['car_id'], unique=False)
    op.create_index(op.f('ix_fuel_log_date'), 'fuel_log', ['date'], unique=False)
    op.create_index('ix_fuel_logs_car_date', 'fuel_log', ['car_id', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fuel_logs_car_date', table_name='fuel_log')
    op.drop_index(op.f('ix_fuel_log_date'), table_name='fuel_log')
    op.drop_index(op.f('ix_fuel_log_car_id'), table_name='fuel_log')
    op.drop_table('fuel_log')
    # ### end Alembic commands ###
