"""create_model_service_item_name

Revision ID: b537bc52c046
Revises: 101e35174ea7
Create Date: 2026-05-07 15:03:54.829162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import uuid


# revision identifiers, used by Alembic.
revision: str = 'b537bc52c046'
down_revision: Union[str, None] = '101e35174ea7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_item_name',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('service_item', sa.Column('service_item_name_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('uq_service_item_car_name'), 'service_item', type_='unique')
    op.create_unique_constraint('uq_service_item_car_name', 'service_item', ['car_id'])
    op.create_index(op.f('ix_service_item_service_item_name_id'), 'service_item', ['service_item_name_id'], unique=False)
    op.create_foreign_key('service_item_name_id_fkey', 'service_item', 'service_item_name', ['service_item_name_id'], ['id'], ondelete='CASCADE')
    op.drop_column('service_item', 'name')
    op.drop_column('service_item', 'icon')
    # ### end Alembic commands ###

    oil_id = uuid.uuid4()
    air_id = uuid.uuid4()
    fuel_id = uuid.uuid4()

    op.execute(
        sa.text("""
                INSERT INTO service_item_name (id, name, icon)
                VALUES (:oil_id, 'Моторное масло', 'oil'),
                       (:air_id, 'Воздушный фильтр', 'air'),
                       (:fuel_id, 'Топливный фильтр', 'fuel')
                """).bindparams(
            oil_id=oil_id,
            air_id=air_id,
            fuel_id=fuel_id,
        )
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_item', sa.Column('icon', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('service_item', sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.drop_constraint('service_item_name_id_fkey', 'service_item', type_='foreignkey')
    op.drop_index(op.f('ix_service_item_service_item_name_id'), table_name='service_item')
    op.drop_constraint('uq_service_item_car_name', 'service_item', type_='unique')
    op.create_unique_constraint(op.f('uq_service_item_car_name'), 'service_item', ['car_id', 'name'], postgresql_nulls_not_distinct=False)
    op.drop_column('service_item', 'service_item_name_id')
    op.drop_table('service_item_name')
    # ### end Alembic commands ###
