"""create model service_record

Revision ID: cca8c1f5be98
Revises: 9f4193585610
Create Date: 2026-04-23 19:24:05.339416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cca8c1f5be98'
down_revision: Union[str, None] = '9f4193585610'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_record',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('car_id', sa.UUID(), nullable=False),
    sa.Column('service_item_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('mileage_at_service', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('workshop', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('next_service_km', sa.Integer(), nullable=True),
    sa.Column('next_service_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='Date of created'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='Date of last updated'),
    sa.ForeignKeyConstraint(['car_id'], ['car.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_item_id'], ['service_item.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_record_car_id'), 'service_record', ['car_id'], unique=False)
    op.create_index(op.f('ix_service_record_date'), 'service_record', ['date'], unique=False)
    op.create_index(op.f('ix_service_record_service_item_id'), 'service_record', ['service_item_id'], unique=False)
    op.create_index('ix_service_records_car_date', 'service_record', ['car_id', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_service_records_car_date', table_name='service_record')
    op.drop_index(op.f('ix_service_record_service_item_id'), table_name='service_record')
    op.drop_index(op.f('ix_service_record_date'), table_name='service_record')
    op.drop_index(op.f('ix_service_record_car_id'), table_name='service_record')
    op.drop_table('service_record')
    # ### end Alembic commands ###
