"""create model mileage_log

Revision ID: daf16e72481a
Revises: cca8c1f5be98
Create Date: 2026-04-23 19:24:46.541953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'daf16e72481a'
down_revision: Union[str, None] = 'cca8c1f5be98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mileage_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('car_id', sa.UUID(), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=False),
    sa.Column('source', postgresql.ENUM('MANUAL', 'OBD', 'SERVICE', name='mileagelogsenum'), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='Date of created'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='Date of last updated'),
    sa.ForeignKeyConstraint(['car_id'], ['car.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mileage_log_car_id'), 'mileage_log', ['car_id'], unique=False)
    op.create_index(op.f('ix_mileage_log_recorded_at'), 'mileage_log', ['recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mileage_log_recorded_at'), table_name='mileage_log')
    op.drop_index(op.f('ix_mileage_log_car_id'), table_name='mileage_log')
    op.drop_table('mileage_log')
    # ### end Alembic commands ###
